Home work
Apoerin/test pull request #4
Opened 2018-10-20 17:06 UTC by Apoerin

![image](https://user-images.githubusercontent.com/44097858/47258422-abb00f00-d4a3-11e8-9150-c6cc7f53bf6c.png)

2018-10-20 17:07 UTC, Apoerin commented
![image](https://user-images.githubusercontent.com/44097858/47258434-bbc7ee80-d4a3-11e8-95bb-668c01968b5e.png)

2018-10-21 19:17 UTC, spolischook requested changes
Missed name attribute for form fields

2018-10-21 19:17 UTC, spolischook commented on HW2/.gitignore
> +#folder idea
Use only one gitignore in the root of project

2018-10-21 19:17 UTC, spolischook commented on HW2/form.html
> +                    <input type="text" id="iduser" placeholder="725">
Use it readonly or disabled

2018-10-21 19:17 UTC, spolischook commented on HW2/form.html
> +                    <input type="Password" id="password">
```suggestion
                    <input type="password" id="password">
```

2018-10-21 19:17 UTC, spolischook commented on HW2/form.html
> +                    We'll remove your public profile email and use 1978331+username@user.noreply.localhost
This text is hang, wrap it

2018-10-21 19:17 UTC, spolischook commented on HW2/form.html
> +                    <input name="surprise" type="hidden">
value is missing here

2018-10-21 19:17 UTC, spolischook commented on HW2/form.html
> +                    <select name="country">
value is missing for options

2018-10-21 19:17 UTC, spolischook commented on HW2/form.html
> +</html>
![settings_025](https://user-images.githubusercontent.com/1978331/47271198-08342c80-d57f-11e8-9078-2af9e694ea2f.png)

2018-10-21 20:07 UTC, spolischook commented on HW2/form.html
> +                        <option value="choose">- Choose your country -</option>
:sun_with_face:

2018-10-22 19:15 UTC, merged