Home work
Apoerin/test pull request #5
Opened 2018-11-04 09:55 UTC by Apoerin

![theatre_main](https://user-images.githubusercontent.com/44097858/47962661-8afdc280-e028-11e8-8ffa-2acdbcfd676c.png)

2018-11-04 20:08 UTC, yana-tsulya commented on HW3/main.html
> +            <span>Назва новини</span>
ось це має бути через heading

2018-11-04 20:09 UTC, yana-tsulya commented on HW3/main.html
> +            <hr>
hr краще не використовувати, краще добав додатковий враппер для інфи нижче і повісь на нього бордер-топ)

2018-11-04 20:10 UTC, yana-tsulya commented on HW3/main.html
> +        <ul class="footer-nav">
ось це також можна в nav звернути

2018-11-04 20:12 UTC, yana-tsulya commented on HW3/main.html
> +        <h1><a href="" name="top"><img src="images/logo.png" alt="Theatre"></a></h1>
Назву сайту потрібно добавляти/ховати поряд з лого)

2018-11-04 20:14 UTC, Apoerin commented on HW3/main.html
> +        <ul class="footer-nav">
> ось це також можна в nav звернути

вместо diva обернутьв nav?

2018-11-04 20:16 UTC, yana-tsulya commented on HW3/main.html
> +            <li><a href=""><i class="fab fa-vk"></i></a></li>
те саме що і з лого, треба завжди вказувати якийсь текст в лінках, це як гуд практіс))

2018-11-04 20:18 UTC, yana-tsulya commented on HW3/style.css
> +    min-width: 100%;
для html і body завжди вказує width: 100% щоб не появлялась неочікувана вертикальна прокрутка)

2018-11-04 20:20 UTC, yana-tsylinska commented on HW3/style.css
> +.dropdown li {
дивна назва для класу, конкретизуй трохи, я так розумію це lang-dropdown?

2018-11-04 20:22 UTC, Apoerin commented on HW3/style.css
> +.dropdown li {
> дивна назва для класу, конкретизуй трохи, я так розумію це lang-dropdown?

да, только я не поняла пока как ее выпадающей сделать

2018-11-04 20:23 UTC, yana-tsylinska commented on HW3/style.css
> +header {
не треба вішита стилі на елементи, header-ів на сторінці може бути багато, краще добавляй спеціальний клас

2018-11-04 20:23 UTC, yana-tsylinska commented on HW3/style.css
> +article {
те саме що з хедером)

2018-11-20 21:03 UTC, yana-tsylinska requested changes

2018-11-20 21:03 UTC, yana-tsylinska commented on HW3/main.html
> +                <a href=""><span class="buy">купити квиток</span></a>
воу, а ось це не спрацює, не можна вкладати лінку в лінку або кнопку, у випадку вкладених лінок - браузер закриє попередню лінку перед початком наступної а далі взагалі не знаю як поведе себе(можеш глянути структуру в дев-тулз))

2018-12-02 16:54 UTC, merged